### ISSUE TITLE
You're not an Engineer, not even close, Lyeb

### ISSUE THREAD

**Issue by ghost** [Liebranca/bitter#7]
@Liebranca  You are not an Engineer. 
You falsely claimed to be an "engineer" in of of your videos. Engineering is not about sitting behind a screen, and pressing keys on a keyboard to write code. No, engineering is far more serious . Engineering is about designing and building real entities, like turbines or buildings. Software developers have this tendency to make huge and false claims these days. They are not engineers, and will never be engineers, not even close.

**Comment by Liebranca** [comment]
I don't argue with deleted accounts.
